namespace Chessy.Model.Enum
{
    public enum LessonTypes
    {
        None,

        YouNeedDestroyKing,
        ThatIsYourSpawn,
        SettingKing,
        PickingGod,
        SettingGod,
        SettingPawn,
        HoldPressWarrior,
        OpeningTown,
        TryBuyingHouse,
        ClickAtYourPawn,
        ShiftPawnHere,
        RelaxExtractPawn,
        StepAwayFromWoodcutter,
        BuildHouseForWarrior,
        SeedingPawn,
        Install1WarriorsNextToTheRiver,
        Build1Farms,
        GiveTakePickPawn,
        ExtractHill,
        NeedBuildSmelterAndMeltOre,
        ClickBuyMarketInTown,
        GiveIronAxe,
        ComeToYourKing,
        //ThatsYourEffects,
        //ThatsYourDamage,
        //ClickDefend,
        UniqueAttackInfo,
        LookInfoAboutSun,
        Kill1Enemy,
        //GiveStaff,
        //GiveBowCrossbow,
        //GiveShield,
        //GiveSword,
        //PawnFireAdultForest,
        ClickWindInfo,
        //ChangeDirectionWind,
        MenuInfo,

        End,
    }
}