namespace Chessy.Model.Enum
{
    public enum LessonTypes
    {
        None,

        YouNeedDestroyKing,
        ThatIsYourSpawn,
        SettingKing,
        PickingGod,
        SettingGod,
        SettingPawn,
        HoldPressTown,
        OpeningTown,
        TryBuyingHouse,
        ClickAtYourPawn,
        ShiftPawnHere,
        RelaxExtractPawn,
        StepAwayFromWoodcutter,
        BuildHouses,
        SeedingPawn,
        Install1WarriorsNextToTheRiver,
        Build3Farms,
        GiveTakePickPawn,
        ExtractHill,
        NeedBuildSmelterAndMeltOre,
        ClickBuyMarketInTown,
        GiveIronAxe,
        ComeToYourKing,
        //ThatsYourEffects,
        //ThatsYourDamage,
        //ClickDefend,
        UniqueAttackInfo,
        LookInfoAboutSun,
        Kill1Enemy,
        GiveStaff,
        GiveBowCrossbow,
        GiveShield,
        GiveSword,
        //PawnFireAdultForest,
        ClickWindInfo,
        //ChangeDirectionWind,
        MenuInfo,

        End,
    }
}