namespace Chessy.Game.Enum
{
    public enum LessonTypes
    {
        None,

        YouNeedDestroyKing,
        ThatIsYourSpawn,
        SettingKing,
        PickingGod,
        SettingGod,
        SettingPawn,
        OpeningTown,
        TryBuyingHouse,
        ClickAtYourPawn,
        HoldPressReady,
        ShiftPawnHere,
        RelaxExtractPawn,
        StepAwayFromWoodcutter,
        BuildHouses,
        SeedingPawn,
        Install3WarriorsNextToTheRiver,
        Build3Farms,
        GiveTakePickPawn,
        ExtractHill,
        NeedBuildSmelterAndMeltOre,
        ClickBuyMarketInTown,
        GiveIronAxe,
        ComeToYourKing,
        ThatsYourEffects,
        ThatsYourDamage,
        ClickDefend,
        UniqueAttackInfo,
        LookInfoAboutSun,
        Kill1Enemy,
        GiveStaff,
        GiveBowCrossbow,
        GiveShield,
        GiveSword,
        PawnFireAdultForest,
        ClickWindInfo,
        ChangeDirectionWind,
        MenuInfo,

        End,
    }
}